In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
import math
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
data=pd.read_csv('/kaggle/input/mnist-digit-recognizer/train.csv')

In [ ]:
data.head()

In [ ]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [ ]:
X_train[:,0].shape


In [108]:
 def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0
def sigmoid(Z):
    return np.exp(Z)/(1+np.exp(Z))
def tanh(Z)
    return (np.exp(Z)-np.exp(-Z))/(np.exp(Z)+np.exp(-Z))
def 
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [109]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [111]:
W1,b1,W2,b2=gradient_descent(X_train,Y_train,0.1,500)
print(W1,W2,b1,b2)

Iteration:  0
[9 7 7 ... 9 9 7] [4 7 7 ... 1 2 6]
0.11260975609756098
Iteration:  10
[5 7 6 ... 3 3 7] [4 7 7 ... 1 2 6]
0.13846341463414635
Iteration:  20
[5 7 6 ... 3 3 0] [4 7 7 ... 1 2 6]
0.20504878048780487
Iteration:  30
[3 7 4 ... 3 3 2] [4 7 7 ... 1 2 6]
0.2867560975609756
Iteration:  40
[3 7 4 ... 3 3 2] [4 7 7 ... 1 2 6]
0.35080487804878047
Iteration:  50
[3 7 4 ... 1 3 2] [4 7 7 ... 1 2 6]
0.40531707317073173
Iteration:  60
[3 7 4 ... 1 3 2] [4 7 7 ... 1 2 6]
0.44734146341463416
Iteration:  70
[3 7 4 ... 1 3 2] [4 7 7 ... 1 2 6]
0.48760975609756096
Iteration:  80
[4 7 4 ... 1 3 2] [4 7 7 ... 1 2 6]
0.5244878048780488
Iteration:  90
[4 7 4 ... 1 3 2] [4 7 7 ... 1 2 6]
0.5568780487804879
Iteration:  100
[4 7 4 ... 1 3 2] [4 7 7 ... 1 2 6]
0.5874878048780487
Iteration:  110
[4 7 4 ... 1 3 2] [4 7 7 ... 1 2 6]
0.6124878048780488
Iteration:  120
[4 7 4 ... 1 6 2] [4 7 7 ... 1 2 6]
0.6338536585365854
Iteration:  130
[4 7 9 ... 1 2 2] [4 7 7 ... 1 2 6]
0.6517560975609756
Iteration: